name: build
on: [push]

env:
  ATLAS_PROJECT_ID: 61d3f66b516c9a03d00e09a1
  ATLAS_APP_ID_PROD: cicd-demo-prod-ayrvk
  ATLAS_APP_ID_QA: cicd-demo-qa-uzann
  ATLAS_APP_ID_DEV_NAME_PREFIX: cicd-demo
  
jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install the Atlas App Services (Realm) CLI & authenticate"
      run: |
           npm install -g mongodb-realm-cli
           realm-cli login --api-key="${{ secrets.ATLAS_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.ATLAS_API_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com
    - name: "Is this a push to the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
           echo "ATLAS_APP_ID=$ATLAS_APP_ID_PROD" >> $GITHUB_ENV
           cd atlas-app
           sed -i txt 's/"environment": ".*"/"environment": "production"/' realm_config.json
    - name: "Is this a push to the Staging branch?"
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: |
           echo "ATLAS_APP_ID=$ATLAS_APP_ID_QA" >> $GITHUB_ENV
           cd atlas-app
           sed -i txt 's/"environment": ".*"/"environment": "qa"/' realm_config.json
    - name: "Is this a push to a feature branch?"
      if: ${{ !env.ATLAS_APP_ID && github.event_name == 'push' }}
      run: | 
           # Create a new environment variable to store the name of the feature branch
           ref=$(echo ${{ github.ref }})
           branch=$(echo "${ref##*/}")
           echo "FEATURE_BRANCH=$ATLAS_APP_ID_DEV_NAME_PREFIX-$branch" >> $GITHUB_ENV
           cd atlas-app
           output=$(realm-cli apps ls | grep $ATLAS_APP_ID_DEV_NAME_PREFIX-$branch- | sed -e 's/ //g' | sed -e 's/(.*)//')
           if [[ $output == *null ]]; then
              echo "No Atlas app found for this branch. A new app will be pushed later in this workflow"
           else
              echo "Atlas app $output was found for this branch. Updates will be pushed to the existing app later in this workflow"
              app_id=$(echo $output)
              echo "ATLAS_APP_ID=$app_id" >> $GITHUB_ENV
           fi
    - name: "Push updated copy of the Atlas app for existing apps (Main, Staging, or Feature branches)"
      if: ${{ env.ATLAS_APP_ID }}
      run: | 
           cd atlas-app
           realm-cli push --remote="${{ env.ATLAS_APP_ID }}" -y
    - name: "Create a new Atlas app for feature branches where the app does not yet exist"
      if: ${{ env.ATLAS_APP_ID == null && github.event_name == 'push' }}
      run: | 
           cd atlas-app
           sed -i txt 's/"name": ".*"/"name": "${{ env.FEATURE_BRANCH }}"/' realm_config.json
           sed -i txt 's/"environment": ".*"/"environment": "development"/' realm_config.json
           sed -i txt '/"app_id".*$/d' realm_config.json
           realm-cli push -y --project $ATLAS_PROJECT_ID
